### PR TITLE
Add examples of SQLite and DataMapper

### PR DESCRIPTION
**Pull request by tannerwelsh**
Inspired/stolen from https://github.com/codeunion/Wall-B/wiki. Wanted to move this info out of the wiki and into its appropriate home, which (I think) is here.

### CODE REVIEW

**Comment by tannerwelsh** [comment]
@zspencer or @jfarmer any reasons not to add these examples? Mind giving a quick scan?

**Comment by zspencer** [comment]
Nice.
Could these be squashed into a single coherent commit?

**Comment by tannerwelsh** [comment]
They sure can!

**Comment by zspencer** [comment]
:party: :trumpet:

**Comment by tannerwelsh** [comment]
Merging...

**Pull request merged**
